name: Run LAVA tests

on:
  push:
    branches: [ "main", "wip/detlev/t44031-add-ci-debug" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  submit-job:

    runs-on: ubuntu-latest
    # TODO: Limit to the correct permission
    permissions:
      actions: write
      checks: write

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'cazou/cros-codecs-tests'
    - name: Retrieve test results
      # lavacli doesn't support retrieving results in the JUnit format. Use the REST API
      run: "curl -H \"Authorization: Token ${{ secrets.LAVA_TOKEN }}\" https://staging.lava.collabora.dev/api/v0.2/jobs/515839/junit/ > results-junit.xml"
    - name: Test results
      uses: cazou/test-reporter@fix-split-on-undefined
      with:
        name: Cros-codecs tests
        path: '*.xml'
        reporter: java-junit
        fail-on-error: true
