name: Run LAVA tests

on:
  push:
    branches: [ "main", "wip/detlev/t44031-add-ci" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libva-dev
        version: 1.0
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-features --examples --release
    - name: Upload built binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ccdec-bin
        path: target/release/examples/ccdec
    # TODO: Upload ccdec to a public server

  submit-job:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install lavacli
      run: sudo apt-get install lavacli
    - name: Add lava identity
      run: lavacli identities add --token ${{ secrets.LAVA_TOKEN }} --uri https://staging.lava.collabora.dev/RPC2 --username detlev ci
    - uses: actions/checkout@v3
      with:
        repository: 'cazou/cros-codecs-tests'
    - name: Submit job
      run: lavacli -i ci jobs submit template.yaml
